"""
Bridge Volume Tracker — Dune API Pipeline
==========================================
크로스체인 브릿지 볼륨, 체인별 순유입/유출 추적.
"""

import os, json, csv, time, requests
from datetime import datetime, timezone, timedelta

DUNE_API_KEY = os.environ.get("DUNE_API_KEY", "")
BASE_URL = "https://api.dune.com/api/v1"
OUTPUT_DIR = "data/bridge-flow"
HEADERS = {"x-dune-api-key": DUNE_API_KEY, "Content-Type": "application/json"}

QUERY_BRIDGE_DAILY = """
SELECT
  DATE(block_time) AS date,
  destination_chain,
  SUM(amount_usd) AS volume_usd,
  COUNT(*) AS tx_count
FROM bridge.flows
WHERE block_time >= NOW() - INTERVAL '100' DAY
  AND amount_usd > 0
GROUP BY 1, 2
ORDER BY 1, 2
"""

QUERY_BRIDGE_PROTOCOLS = """
SELECT
  project AS protocol,
  SUM(amount_usd) AS volume_usd,
  COUNT(*) AS tx_count
FROM bridge.flows
WHERE block_time >= NOW() - INTERVAL '30' DAY
  AND amount_usd > 0
GROUP BY 1
ORDER BY 2 DESC
LIMIT 15
"""

def execute_query(sql, name):
    print(f"\n[{name}] Executing query...")
    resp = requests.post(f"{BASE_URL}/query/execute/sql", headers=HEADERS,
        json={"query_sql": sql, "performance": "medium"}, timeout=30)
    if resp.status_code != 200:
        print(f"  ✗ Execute failed: {resp.status_code} {resp.text[:300]}")
        return None
    eid = resp.json().get("execution_id")
    if not eid: return None
    print(f"  → execution_id: {eid}")
    for attempt in range(60):
        time.sleep(5)
        r = requests.get(f"{BASE_URL}/execution/{eid}/results", headers=HEADERS,
            params={"limit": 50000}, timeout=30)
        if r.status_code != 200: continue
        result = r.json(); state = result.get("state", "")
        if state == "QUERY_STATE_COMPLETED":
            rows = result.get("result", {}).get("rows", [])
            print(f"  ✓ Got {len(rows)} rows"); return rows
        elif state == "QUERY_STATE_FAILED":
            print(f"  ✗ Failed: {result.get('error','')}"); return None
        elif attempt % 4 == 0:
            print(f"  ⏳ {state} ({attempt+1})...")
    return None

def generate_js(daily_rows, protocol_rows):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    js = f"""// Auto-generated by fetch_bridge_flow.py
// Last updated: {now}
const BRIDGE_DAILY_DATA = {json.dumps(daily_rows or [], indent=2, default=str)};
const BRIDGE_PROTOCOLS = {json.dumps(protocol_rows or [], indent=2, default=str)};
"""
    fp = os.path.join(OUTPUT_DIR, "bridge_flow_data.js")
    with open(fp, "w", encoding="utf-8") as f: f.write(js)
    print(f"\n  ✓ Generated {fp}")

def main():
    print("=" * 55)
    print("  Bridge Volume Tracker — Dune Pipeline")
    print(f"  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print("=" * 55)
    if not DUNE_API_KEY:
        print("\n⚠ DUNE_API_KEY not set! Generating sample...")
        generate_sample(); return

    daily = execute_query(QUERY_BRIDGE_DAILY, "Bridge Daily")
    protocols = execute_query(QUERY_BRIDGE_PROTOCOLS, "Bridge Protocols")
    generate_js(daily, protocols)

    meta = {"last_updated": datetime.now(timezone.utc).isoformat(),
            "rows": {"daily": len(daily or []), "protocols": len(protocols or [])}}
    with open(os.path.join(OUTPUT_DIR, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    print("\n✅ Pipeline complete!")

def generate_sample():
    import math
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    seed = 55
    def rand():
        nonlocal seed; seed = (seed * 16807) % 2147483647; return (seed - 1) / 2147483646
    chains = ['Arbitrum','Base','Optimism','Solana','Polygon','BSC','zkSync','Avalanche','Scroll','Linea']
    daily = []
    for i in range(90):
        d = datetime(2024, 12, 10) + timedelta(days=i)
        for c in chains:
            vol = (30 + rand() * 70 + (rand() * 200 if rand() > 0.93 else 0)) * 1e6
            daily.append({"date": d.strftime("%Y-%m-%d"), "destination_chain": c,
                          "volume_usd": round(vol), "tx_count": int(80 + rand() * 200)})
    protocols = [
        {"protocol":"Stargate","volume_usd":3.2e9,"tx_count":45000},
        {"protocol":"Across","volume_usd":2.8e9,"tx_count":38000},
        {"protocol":"Wormhole","volume_usd":1.9e9,"tx_count":22000},
        {"protocol":"Synapse","volume_usd":1.1e9,"tx_count":15000},
        {"protocol":"Hop","volume_usd":0.8e9,"tx_count":12000},
        {"protocol":"Orbiter","volume_usd":0.6e9,"tx_count":9000},
        {"protocol":"Celer","volume_usd":0.4e9,"tx_count":5000},
    ]
    generate_js(daily, protocols)
    print("✅ Sample data generated!")

if __name__ == "__main__":
    main()
