"""
Smart Money & Whale Tracker — Dune API Pipeline
================================================
$1M+ 대형 전송, CEX 순유입/유출, 고래 매집 토큰 추적.
"""

import os, json, csv, time, requests, math
from datetime import datetime, timezone, timedelta

DUNE_API_KEY = os.environ.get("DUNE_API_KEY", "")
BASE_URL = "https://api.dune.com/api/v1"
OUTPUT_DIR = "data/smart-money"
HEADERS = {"x-dune-api-key": DUNE_API_KEY, "Content-Type": "application/json"}

# ─── SQL Queries ─────────────────────────────────

QUERY_WHALE_DAILY = """
SELECT
  date_trunc('day', block_time) AS date,
  COUNT(*) AS whale_count,
  SUM(amount_usd) AS whale_volume_usd
FROM tokens.transfers
WHERE blockchain = 'ethereum'
  AND block_date >= CURRENT_DATE - INTERVAL '100' DAY
  AND amount_usd >= 1000000
GROUP BY 1
ORDER BY 1
"""

QUERY_TOP_TOKENS = """
SELECT
  symbol AS token,
  SUM(amount_usd) AS volume,
  COUNT(*) AS tx_count
FROM tokens.transfers
WHERE blockchain = 'ethereum'
  AND block_date >= CURRENT_DATE - INTERVAL '30' DAY
  AND amount_usd >= 1000000
  AND symbol IS NOT NULL
GROUP BY 1
ORDER BY 2 DESC
LIMIT 15
"""

QUERY_RECENT_LARGE = """
SELECT
  block_time,
  symbol AS token,
  amount_usd,
  CAST("from" AS VARCHAR) AS from_addr,
  CAST("to" AS VARCHAR) AS to_addr
FROM tokens.transfers
WHERE blockchain = 'ethereum'
  AND block_date >= CURRENT_DATE - INTERVAL '2' DAY
  AND amount_usd >= 1000000
ORDER BY amount_usd DESC
LIMIT 20
"""

# ─── API ─────────────────────────────────────────

def execute_query(sql, name):
    print(f"\n[{name}] Executing query...")
    resp = requests.post(f"{BASE_URL}/query/execute/sql", headers=HEADERS,
        json={"query_sql": sql, "performance": "medium"}, timeout=30)
    if resp.status_code != 200:
        print(f"  ✗ Execute failed: {resp.status_code} {resp.text[:300]}")
        return None
    eid = resp.json().get("execution_id")
    if not eid:
        print(f"  ✗ No execution_id")
        return None
    print(f"  → execution_id: {eid}")
    for attempt in range(60):
        time.sleep(5)
        r = requests.get(f"{BASE_URL}/execution/{eid}/results", headers=HEADERS,
            params={"limit": 10000}, timeout=30)
        if r.status_code != 200: continue
        result = r.json()
        state = result.get("state", "")
        if state == "QUERY_STATE_COMPLETED":
            rows = result.get("result", {}).get("rows", [])
            print(f"  ✓ Got {len(rows)} rows")
            return rows
        elif state == "QUERY_STATE_FAILED":
            print(f"  ✗ Failed: {result.get('error','')}")
            return None
        elif attempt % 4 == 0:
            print(f"  ⏳ {state} (attempt {attempt+1})...")
    print("  ✗ Timeout")
    return None

def save_csv(rows, filename):
    if not rows: return
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    fp = os.path.join(OUTPUT_DIR, filename)
    with open(fp, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader(); w.writerows(rows)
    print(f"  ✓ Saved {fp}")

def generate_js(daily, tokens, recent):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    # Process daily
    daily_out = []
    for r in (daily or []):
        daily_out.append({
            "date": str(r.get("date",""))[:10],
            "whale_count": int(r.get("whale_count", 0)),
            "whale_volume_usd": round(float(r.get("whale_volume_usd", 0)), 2)
        })
    # Process tokens
    tokens_out = []
    total = sum(float(t.get("volume",0)) for t in (tokens or []))
    for t in (tokens or []):
        v = float(t.get("volume", 0))
        tokens_out.append({
            "token": t.get("token", "?"),
            "volume": round(v, 2),
            "count": int(t.get("tx_count", 0)),
            "pct": round(v / total * 100, 1) if total > 0 else 0
        })
    # Process recent
    recent_out = []
    for r in (recent or []):
        recent_out.append({
            "time": str(r.get("block_time",""))[:16],
            "token": r.get("token","?"),
            "amount": round(float(r.get("amount_usd",0)),2),
            "from": r.get("from_addr",""),
            "to": r.get("to_addr","")
        })

    js = f"""// Auto-generated by fetch_smart_money.py
// Last updated: {now}
const WHALE_DAILY_DATA = {json.dumps(daily_out, indent=2)};
const WHALE_TOP_TOKENS = {json.dumps(tokens_out, indent=2)};
const WHALE_RECENT_TRANSFERS = {json.dumps(recent_out, indent=2)};
"""
    fp = os.path.join(OUTPUT_DIR, "smart_money_data.js")
    with open(fp, "w", encoding="utf-8") as f: f.write(js)
    print(f"\n  ✓ Generated {fp}")

# ─── Main ────────────────────────────────────────

def main():
    print("=" * 55)
    print("  Smart Money & Whale Tracker — Dune Pipeline")
    print(f"  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print("=" * 55)

    if not DUNE_API_KEY:
        print("\n⚠ DUNE_API_KEY not set! Generating sample data...")
        generate_sample()
        return

    daily = execute_query(QUERY_WHALE_DAILY, "Whale Daily")
    save_csv(daily, "whale_daily.csv")
    tokens = execute_query(QUERY_TOP_TOKENS, "Top Tokens")
    save_csv(tokens, "whale_top_tokens.csv")
    recent = execute_query(QUERY_RECENT_LARGE, "Recent Large")
    save_csv(recent, "whale_recent.csv")
    generate_js(daily, tokens, recent)

    meta = {"last_updated": datetime.now(timezone.utc).isoformat(),
            "rows": {"daily": len(daily or []), "tokens": len(tokens or []), "recent": len(recent or [])}}
    with open(os.path.join(OUTPUT_DIR, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    print("\n✅ Pipeline complete!")

def generate_sample():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    seed = 77
    def rand():
        nonlocal seed; seed = (seed * 16807) % 2147483647; return (seed - 1) / 2147483646
    data = []
    for i in range(90):
        d = datetime(2025,1,1) + timedelta(days=i)
        c = int(80 + rand()*120 + (rand()*200 if rand()>0.9 else 0))
        v = c * (2 + rand()*8) * 1e6
        ci = v * (0.2 + rand()*0.3); co = v * (0.15 + rand()*0.35)
        data.append({"date": d.strftime("%Y-%m-%d"), "whale_count": c,
                      "whale_volume_usd": round(v), "cex_inflow_usd": round(ci),
                      "cex_outflow_usd": round(co), "cex_net_usd": round(ci - co)})
    tokens = [{"token":"USDT","volume":28.4e9,"count":892},{"token":"USDC","volume":21.2e9,"count":743},
              {"token":"ETH","volume":15.8e9,"count":621},{"token":"WBTC","volume":8.9e9,"count":312},
              {"token":"stETH","volume":6.2e9,"count":198},{"token":"DAI","volume":4.1e9,"count":156},
              {"token":"LINK","volume":2.8e9,"count":134},{"token":"UNI","volume":1.9e9,"count":98},
              {"token":"AAVE","volume":1.4e9,"count":72},{"token":"MKR","volume":0.98e9,"count":45}]
    total = sum(t["volume"] for t in tokens)
    for t in tokens: t["pct"] = round(t["volume"]/total*100, 1)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    js = f"""// Sample data\n// Generated: {now}
const WHALE_DAILY_DATA = {json.dumps(data, indent=2)};
const WHALE_TOP_TOKENS = {json.dumps(tokens, indent=2)};
const WHALE_RECENT_TRANSFERS = [];
"""
    with open(os.path.join(OUTPUT_DIR, "smart_money_data.js"), "w") as f: f.write(js)
    print("✅ Sample data generated!")

if __name__ == "__main__":
    main()
